import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <section className="body-font text-gray-800">
          <div className="container mx-auto flex flex-col items-center px-5 py-24 md:flex-row">
            <div className="mb-10 w-5/6 md:mb-0 md:w-1/2 lg:w-full lg:max-w-lg">
              <img
                className="rounded border-4 border-gray-800 object-cover object-center"
                alt="hero"
                src="https://images.unsplash.com/photo-1502691876148-a84978e59af8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"
              />
            </div>
            <div className="flex flex-col items-center text-center md:w-1/2 md:items-start md:pl-16 md:text-left lg:flex-grow lg:pl-24">
              <h1 className="title-font mb-4 text-3xl font-medium text-purple-600 sm:text-4xl">
                Boka din målare nu!
              </h1>
              <p className="mb-8 leading-relaxed">
                Du får en offert direkt och kan boka din målare inom 48 timmar.
              </p>
              <div className="flex w-full items-end justify-center md:justify-start">
                <div className="relative mr-4 w-2/4 lg:w-full xl:w-1/2">
                  <label
                    htmlFor="hero-field"
                    className="text-sm leading-7 text-gray-400"
                  >
                    Privatperson eller Företag
                  </label>
                  <select
                    id="country"
                    name="country"
                    autoComplete="country-name"
                    className="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                  >
                    <option>Privatperson</option>
                    <option>Företag</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
